//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfsTools.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfsTools.Resourses.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value not bound to option name is defined with a bad format..
        /// </summary>
        internal static string BadFormatConversionErrorFormat1 {
            get {
                return ResourceManager.GetString("BadFormatConversionErrorFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined with a bad format..
        /// </summary>
        internal static string BadFormatConversionErrorFormat2 {
            get {
                return ResourceManager.GetString("BadFormatConversionErrorFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string BadFormatTokenErrorFormat {
            get {
                return ResourceManager.GetString("BadFormatTokenErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string BadVerbSelectedErrorFormat {
            get {
                return ResourceManager.GetString("BadVerbSelectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create EFS directory.
        /// </summary>
        internal static string CreateEFSDirectory {
            get {
                return ResourceManager.GetString("CreateEFSDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error. {0}.
        /// </summary>
        internal static string CriticalErrorFormat {
            get {
                return ResourceManager.GetString("CriticalErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path.
        /// </summary>
        internal static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more information on a specific command..
        /// </summary>
        internal static string DisplayMoreInformationOnASpecificCommand {
            get {
                return ResourceManager.GetString("DisplayMoreInformationOnASpecificCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        internal static string DisplayThisHelpScreen {
            get {
                return ResourceManager.GetString("DisplayThisHelpScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        internal static string DisplayVersionInformation {
            get {
                return ResourceManager.GetString("DisplayVersionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t create all parent directories.
        /// </summary>
        internal static string DontCreateAllParentDirectories {
            get {
                return ResourceManager.GetString("DontCreateAllParentDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR(S).
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Response CRC Expected: {0:X} - Received: {1:X}.
        /// </summary>
        internal static string HdlcInvalidResponseCrcFormat {
            get {
                return ResourceManager.GetString("HdlcInvalidResponseCrcFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Can&apos;t find magic string &apos;MCFG&apos;.
        /// </summary>
        internal static string MbnExtractorInvalidFormatCantFindMagicString {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatCantFindMagicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. ELF segment with data not exist.
        /// </summary>
        internal static string MbnExtractorInvalidFormatElfDataNotExist {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatElfDataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid header version id.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidHeaderVersionId {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidHeaderVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid header version value.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidHeaderVersionValue {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidHeaderVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid file header magic.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidInvalidFileHeaderMagic {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidInvalidFileHeaderMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid file item size.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidInvalidFileItemSize {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidInvalidFileItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid file size magic.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidInvalidFileSizeMagic {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidInvalidFileSizeMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid NV item size.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidInvalidNvItemSize {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidInvalidNvItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid trailer magic &apos;0x0A&apos;.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidTrailerMagic1 {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidTrailerMagic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid trailer magic &apos;0xA1&apos;.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidTrailerMagic2 {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidTrailerMagic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid trailer magic &apos;MCFG_TRL&apos;.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidTrailerMagicValue {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidTrailerMagicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Invalid trailer size.
        /// </summary>
        internal static string MbnExtractorInvalidFormatInvalidTrailerSize {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatInvalidTrailerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MBN format. Unknown item type.
        /// </summary>
        internal static string MbnExtractorInvalidFormatUnknownItemType {
            get {
                return ResourceManager.GetString("MbnExtractorInvalidFormatUnknownItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value not bound to option name is missing..
        /// </summary>
        internal static string MissingRequiredOptionErrorFormat1 {
            get {
                return ResourceManager.GetString("MissingRequiredOptionErrorFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined with a bad format..
        /// </summary>
        internal static string MissingRequiredOptionErrorFormat2 {
            get {
                return ResourceManager.GetString("MissingRequiredOptionErrorFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has no value..
        /// </summary>
        internal static string MissingValueOptionErrorFormat {
            get {
                return ResourceManager.GetString("MissingValueOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb selected..
        /// </summary>
        internal static string NoVerbSelectedErrorFormat {
            get {
                return ResourceManager.GetString("NoVerbSelectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to exit.
        /// </summary>
        internal static string PressEnterToExit {
            get {
                return ResourceManager.GetString("PressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying modem config....
        /// </summary>
        internal static string QcdmApplyingModemConfig {
            get {
                return ResourceManager.GetString("QcdmApplyingModemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open EFS directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmCantOpenEfsDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmCantOpenEfsDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open EFS file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmCantOpenEfsFileFormat {
            get {
                return ResourceManager.GetString("QcdmCantOpenEfsFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad command.
        /// </summary>
        internal static string QcdmCommandBadCmd {
            get {
                return ResourceManager.GetString("QcdmCommandBadCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad lengths.
        /// </summary>
        internal static string QcdmCommandBadLen {
            get {
                return ResourceManager.GetString("QcdmCommandBadLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad mode.
        /// </summary>
        internal static string QcdmCommandBadMode {
            get {
                return ResourceManager.GetString("QcdmCommandBadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad params.
        /// </summary>
        internal static string QcdmCommandBadParm {
            get {
                return ResourceManager.GetString("QcdmCommandBadParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad SPC mode.
        /// </summary>
        internal static string QcdmCommandBadSpcMode {
            get {
                return ResourceManager.GetString("QcdmCommandBadSpcMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading NV items ....
        /// </summary>
        internal static string QcdmDownloadingNvItems {
            get {
                return ResourceManager.GetString("QcdmDownloadingNvItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad file number.
        /// </summary>
        internal static string QcdmEfsErrorsBadFileNumber {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsBadFileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFS error. Code = {0}.
        /// </summary>
        internal static string QcdmEfsErrorsDefaultFormat {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not empty.
        /// </summary>
        internal static string QcdmEfsErrorsDirectoryNotEmpty {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsDirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory entry not found.
        /// </summary>
        internal static string QcdmEfsErrorsDirEntNotFound {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsDirEntNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not open.
        /// </summary>
        internal static string QcdmEfsErrorsDirNotOpen {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsDirNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists.
        /// </summary>
        internal static string QcdmEfsErrorsFileExist {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent state.
        /// </summary>
        internal static string QcdmEfsErrorsInconsistentState {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsInconsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory entry.
        /// </summary>
        internal static string QcdmEfsErrorsInvalidDirEntry {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsInvalidDirEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        internal static string QcdmEfsErrorsInvalidPath {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence.
        /// </summary>
        internal static string QcdmEfsErrorsInvalidSequence {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsInvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error.
        /// </summary>
        internal static string QcdmEfsErrorsIoError {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsIoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string QcdmEfsErrorsNone {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a directory.
        /// </summary>
        internal static string QcdmEfsErrorsNotDirectory {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsNotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such file or directory.
        /// </summary>
        internal static string QcdmEfsErrorsNotEntry {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsNotEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not nand flash.
        /// </summary>
        internal static string QcdmEfsErrorsNotNandFlash {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsNotNandFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not permitted.
        /// </summary>
        internal static string QcdmEfsErrorsNotPermited {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsNotPermited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string QcdmEfsErrorsOutOfMemory {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsOutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long.
        /// </summary>
        internal static string QcdmEfsErrorsPathTooLong {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        internal static string QcdmEfsErrorsPermissionDenided {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsPermissionDenided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many open directories.
        /// </summary>
        internal static string QcdmEfsErrorsTooManyOpenDirs {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsTooManyOpenDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many open files.
        /// </summary>
        internal static string QcdmEfsErrorsTooManyOpenFiles {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsTooManyOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable info.
        /// </summary>
        internal static string QcdmEfsErrorsUnavailableInfo {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsUnavailableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file type.
        /// </summary>
        internal static string QcdmEfsErrorsUnknownFileType {
            get {
                return ResourceManager.GetString("QcdmEfsErrorsUnknownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on create directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnCreateDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnCreateDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on delete directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnDeleteDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnDeleteDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on delete file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnDeleteFileFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnDeleteFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on download directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnDownloadDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnDownloadDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on download file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnDownloadFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnDownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on fix file names in &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnFixFileNamesFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnFixFileNamesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on open directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnOpenDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnOpenDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on set event mask.
        /// </summary>
        internal static string QcdmErrorOnSetEventMask {
            get {
                return ResourceManager.GetString("QcdmErrorOnSetEventMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on upload directory &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnUploadDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnUploadDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on upload file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string QcdmErrorOnUploadFormat {
            get {
                return ResourceManager.GetString("QcdmErrorOnUploadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting MBN file &apos;{0}&apos; ....
        /// </summary>
        internal static string QcdmExtractingMbnFileFormat {
            get {
                return ResourceManager.GetString("QcdmExtractingMbnFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed file name &apos;{0}&apos; to &apos;{1}&apos; in folder &apos;{2}&apos;.
        /// </summary>
        internal static string QcdmFixFileNameFormat {
            get {
                return ResourceManager.GetString("QcdmFixFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting modem config....
        /// </summary>
        internal static string QcdmGeneratingModemConfig {
            get {
                return ResourceManager.GetString("QcdmGeneratingModemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid log mask.
        /// </summary>
        internal static string QcdmInvalidLogMask {
            get {
                return ResourceManager.GetString("QcdmInvalidLogMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string QcdmInvalidPassword {
            get {
                return ResourceManager.GetString("QcdmInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response.
        /// </summary>
        internal static string QcdmInvalidResponse {
            get {
                return ResourceManager.GetString("QcdmInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response command.
        /// </summary>
        internal static string QcdmInvalidResponseCommand {
            get {
                return ResourceManager.GetString("QcdmInvalidResponseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response length.
        /// </summary>
        internal static string QcdmInvalidResponseLength {
            get {
                return ResourceManager.GetString("QcdmInvalidResponseLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SPC.
        /// </summary>
        internal static string QcdmInvalidSpc {
            get {
                return ResourceManager.GetString("QcdmInvalidSpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing of directory &apos;{0}&apos;:.
        /// </summary>
        internal static string QcdmListOfDirectoryFormat {
            get {
                return ResourceManager.GetString("QcdmListOfDirectoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log &apos;{0}&apos; not supported.
        /// </summary>
        internal static string QcdmLogSubcribingLogNotSupportedErrorFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingLogNotSupportedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message &apos;{0}&apos; not supported.
        /// </summary>
        internal static string QcdmLogSubcribingMessageNotSupportedErrorFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingMessageNotSupportedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcribing to logs: {0} ....
        /// </summary>
        internal static string QcdmLogSubcribingToLogsFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingToLogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully subscribed to the logs: {0}.
        /// </summary>
        internal static string QcdmLogSubcribingToLogsResultFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingToLogsResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcribing to messages: {0} ....
        /// </summary>
        internal static string QcdmLogSubcribingToMessagesFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingToMessagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully subscribed to the messages: {0}.
        /// </summary>
        internal static string QcdmLogSubcribingToMessagesResultFormat {
            get {
                return ResourceManager.GetString("QcdmLogSubcribingToMessagesResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many log lines. Please disable log..
        /// </summary>
        internal static string QcdmManyLogLines {
            get {
                return ResourceManager.GetString("QcdmManyLogLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos; ....
        /// </summary>
        internal static string QcdmProcessingFormat {
            get {
                return ResourceManager.GetString("QcdmProcessingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port is not open.
        /// </summary>
        internal static string QcdmSerialPortIsNotOpen {
            get {
                return ResourceManager.GetString("QcdmSerialPortIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported command response ({0}).
        /// </summary>
        internal static string QcdmUnsupportedCommandResponseFormat {
            get {
                return ResourceManager.GetString("QcdmUnsupportedCommandResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported  subsystem command response ({0}).
        /// </summary>
        internal static string QcdmUnsupportedSubsysCommandResponseFormat {
            get {
                return ResourceManager.GetString("QcdmUnsupportedSubsysCommandResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading NV items ....
        /// </summary>
        internal static string QcdmUploadingNvItems {
            get {
                return ResourceManager.GetString("QcdmUploadingNvItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use serial port &apos;{0}&apos;.
        /// </summary>
        internal static string QcdmUseComPortFormat {
            get {
                return ResourceManager.GetString("QcdmUseComPortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined multiple times..
        /// </summary>
        internal static string RepeatedOptionErrorFormat {
            get {
                return ResourceManager.GetString("RepeatedOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence value not bound to option name is defined with few items than required..
        /// </summary>
        internal static string SequenceOutOfRangeErrorFormat1 {
            get {
                return ResourceManager.GetString("SequenceOutOfRangeErrorFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence option &apos;{0}&apos; is defined with fewer or more items than required..
        /// </summary>
        internal static string SequenceOutOfRangeErrorFormat2 {
            get {
                return ResourceManager.GetString("SequenceOutOfRangeErrorFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is unknown..
        /// </summary>
        internal static string UnknownOptionErrorFormat {
            get {
                return ResourceManager.GetString("UnknownOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
